const compliments = [
    "Tu es beau",
    "Tu es incroyable",
    "Tu es intelligent",
    "Tu es réfléchi",
    "Tu es exceptionnel",
    "Tu es un pro de l'automobile",
    "Tu me fais bien l'amour",
    "J'aime tes yeux qui brillent",
    "J'adore ton ENORME queue",
    "Tu es un pro du code",
    "Tu es un pro des nouvelles technologies",
    "Tu as un cul dur comme le béton",
    "J'aime tes biceps",
    "Tu m'impressionnes",
    "T'as une culture générale hallucinante",
    "J'aime quand tu me lèches",
    "Je t'aime",
    "J'aime être dans tes bras",
    "J'aime quand tu es l'homme de la situation",
    "Tu es l'enfant parfait",
    "Tu es ingénieur (oui c'est un compliment)",
    "Tu es un motard sexy",
    "Tu me rends meilleure",
    "Tu cuisines très bien le houmous",
    "Tu es gentil",
    "Tu es drôle",
    "Tu es quelqu'un de bien",
    "J'aime ton sourire",
    "Tu es unique",
    "J'aime ta pêche",
    "J'aime être ta passagère en moto",
    "Tu fais les créneaux comme un Dieu",
    "Tu conduis tellement bien",
    "Tu manoeuvres comme un pro",
    "Tu es serviable",
    "Tu es un très bon ami",
    "Je suis tellement contente de t'avoir rencontré",
    "Tu me fais rire",
    "J'aime ton grain de beauté sur l'oreille droite",
    "Je t'aime Maxime Olivier Jean-Luc Sabin Guilain Castaing",
    "T'as de beaux yeux verts",
    "Tu es sexy avec tes lunettes de soleil",
    "Tu me séduis quand on va voir le château d'eau à Jönköping",
    "Tu me plaies quand tu essaies de crocheter une serrure",
    "Tu me fais mouiller",
    "J'aime quand tu me fais des vlogs",
    "J'aime quand tu conduis Bebou",
    "J'aime quand tu mets ton doigt dans mon nez",
    "J'aime quand tu t'assieds sur mon visage",
    "J'aime quand tu me frappes avec le préservatif",
    "J'aime quand tu te colles à moi quand tu as une éréction",
    "J'aime quand tu m'envoies des photos de Popol",
    "J'aime quand tu m'envoies des photos de toi en train de faire caca",
    "J'aime quand tu me pètes au visage",
    "J'aime quand tu m'expliques des choses",
    "J'aime quand tu me fais découvrir des films",
    "J'aime prendre ma douche avec toi",
    "J'aime jouer à des jeux-vidéos avec toi",
    "Maxime ? Je t'aime",
    "Maxime ? T'es beau",
    "Tu es bienveillant",
    "Tu me fais mourir de rire",
    "J'aime quand tu apportes une explication scientifique à mes questions",
    "J'aime te faire du pied sous la table",
    "J'aime faire les courses avec toi",
    "J'aime quand tu vas sur Dealabs",
    "J'aime quand tu me grattes le dos",
    "Tu masses très bien",
    "J'aime quand tu rotes et que tu aspires ton rot",
    "Tu es beau quand tu mets des chemises",
    "Avec un polo, tu est trop bo (t'as vu ça rime ? J'aime les rimes)",
    "Ta b*te est délicieuse",
    "Ton sperme est savoureux",
    "Tu es honnête",
    "Tu es responsable",
    "Tu es là pour les gens qui t'entourent",
    "Tu twerkes incroyablement bien",
    "J'aime quand tu dessines des bites",
    "J'aime quand tu joues avec Bâle et Mulhouse",
    "J'aime quand tu viens me voir à l'étranger",
    "Ta moustache est merveilleuse",
    "J'aime les poils que tu as sur les doigts de pied",
    "Tu es respectueux",
    "J'aime quand tu fais des speedtests",
    "J'aime quand tu te plein de la lenteur du wifi",
    "J'aime quand tu te plains de ton wifi hyper rapide",
    "Je suis ravie de t'avoir rencontré",
    "J'aime quand tu mets du houmous sur Popol",
    "J'aime quand tu vas sur le site https://lewifi.fr/",
    "Tu es irrésistible",
    "Tu es adorable",
    "Tu es mignon",
    "Je t'aime mon p'tit keur",
    "Tu es parfait mon motard ingénieur parisien",
    "Je suis tombée sur le charme",
    "J'aime te voir à poil",
    "J'aime ton corps",
    "J'aime tes câlins",
    "J'aime tes bisous",
    "J'aime ton sourire",
    "Je suis heureuse avec toi",
    "Tu me manques <3",
    "Tu me remplis d'amour",
    "ROH MAIS JE T'AIME TELLEMENT",
    "Je reconnais les efforts que tu fais",
    "Tu mérites le bonheur",
    "J'aime quand on fait du vélo ensemble",
    "J'aime être avec toi",
    "J'aime t'entendre parler d'automobile",
    "Tu me séduis quand tu connais le modèle EXACT d'une voiture",
    "Tu me fais perdre mes moyens",
    "J'aime quand tu me demandes si je veux que tu te brosses les dents après avoir mangé un repas non vegan",
    "J'aime quand tu as tes délires (quoicoubeh, no faké, j'en passe et des meilleurs",
];

function afficherCompliment() {
    const index = Math.floor(Math.random() * compliments.length);
    const compliment = compliments[index];
    document.getElementById("compliment").innerText = compliment;
}